/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Anime RPG Bot Admin API
 * OpenAPI spec version: 0.1.0
 */

export type AddMarketItemRequestItemType =
  (typeof AddMarketItemRequestItemType)[keyof typeof AddMarketItemRequestItemType];

export const AddMarketItemRequestItemType = {
  character: "character",
  card: "card",
} as const;
