/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Anime RPG Bot Admin API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface SuccessResponse {
  success: boolean;
  message: string;
}

export interface DashboardStats {
  totalUsers: number;
  totalGroups: number;
  totalCoins: number;
  activeAds: number;
  activeTournaments: number;
  totalCharacters: number;
  totalCards: number;
  premiumUsers: number;
}

export interface User {
  userId: number;
  username?: string | null;
  firstName?: string | null;
  coins: number;
  bank: number;
  xp: number;
  level: number;
  premiumUntil?: string | null;
  joinedAt: string;
  charactersCount: number;
  cardsCount: number;
}

export interface UpdateUserRequest {
  coins?: number;
  bank?: number;
  xp?: number;
  level?: number;
  premiumUntil?: string | null;
}

export interface UsersListResponse {
  users: User[];
  total: number;
  page: number;
  limit: number;
}

export interface Group {
  id: number;
  chatId: string;
  groupName?: string | null;
  addedAt: string;
}

export interface GroupsListResponse {
  groups: Group[];
  total: number;
}

export interface Character {
  id: number;
  name: string;
  rarity: string;
  power: number;
  kills: number;
  skills?: string | null;
  price: number;
  imagePath?: string | null;
}

export interface CreateCharacterRequest {
  name: string;
  rarity: string;
  power: number;
  kills: number;
  skills?: string;
  price: number;
  image?: Blob;
}

export interface CharactersListResponse {
  characters: Character[];
  total: number;
}

export interface Card {
  id: number;
  name: string;
  rarity: string;
  power: number;
  skills?: string | null;
  price: number;
  imagePath?: string | null;
}

export interface CreateCardRequest {
  name: string;
  rarity: string;
  power: number;
  skills?: string;
  price: number;
  image?: Blob;
}

export interface CardsListResponse {
  cards: Card[];
  total: number;
}

export type AdStatus = (typeof AdStatus)[keyof typeof AdStatus];

export const AdStatus = {
  active: "active",
  inactive: "inactive",
} as const;

export interface Ad {
  id: number;
  adText: string;
  status: AdStatus;
  createdAt: string;
}

export type CreateAdRequestStatus =
  (typeof CreateAdRequestStatus)[keyof typeof CreateAdRequestStatus];

export const CreateAdRequestStatus = {
  active: "active",
  inactive: "inactive",
} as const;

export interface CreateAdRequest {
  adText: string;
  status?: CreateAdRequestStatus;
}

export interface AdsListResponse {
  ads: Ad[];
  total: number;
}

export type TournamentStatus =
  (typeof TournamentStatus)[keyof typeof TournamentStatus];

export const TournamentStatus = {
  pending: "pending",
  active: "active",
  ended: "ended",
} as const;

export type TournamentRewardType =
  (typeof TournamentRewardType)[keyof typeof TournamentRewardType];

export const TournamentRewardType = {
  coins: "coins",
  card: "card",
  character: "character",
  premium: "premium",
} as const;

export interface Tournament {
  id: number;
  name: string;
  status: TournamentStatus;
  rewardType: TournamentRewardType;
  rewardValue: string;
  participantCount: number;
  createdAt: string;
}

export type CreateTournamentRequestRewardType =
  (typeof CreateTournamentRequestRewardType)[keyof typeof CreateTournamentRequestRewardType];

export const CreateTournamentRequestRewardType = {
  coins: "coins",
  card: "card",
  character: "character",
  premium: "premium",
} as const;

export interface CreateTournamentRequest {
  name: string;
  rewardType: CreateTournamentRequestRewardType;
  rewardValue: string;
}

export interface TournamentsListResponse {
  tournaments: Tournament[];
  total: number;
}

export type MarketItemItemType =
  (typeof MarketItemItemType)[keyof typeof MarketItemItemType];

export const MarketItemItemType = {
  character: "character",
  card: "card",
} as const;

export interface MarketItem {
  id: number;
  itemType: MarketItemItemType;
  itemId: number;
  price: number;
  sellerId?: number | null;
  itemName?: string | null;
  itemRarity?: string | null;
  itemPower?: number | null;
  imagePath?: string | null;
}

export type AddMarketItemRequestItemType =
  (typeof AddMarketItemRequestItemType)[keyof typeof AddMarketItemRequestItemType];

export const AddMarketItemRequestItemType = {
  character: "character",
  card: "card",
} as const;

export interface AddMarketItemRequest {
  itemType: AddMarketItemRequestItemType;
  itemId: number;
  price: number;
}

export interface MarketListResponse {
  items: MarketItem[];
  total: number;
}

export interface Guild {
  id: number;
  name: string;
  ownerId: number;
  level: number;
  coins: number;
  memberCount: number;
}

export interface GuildsListResponse {
  guilds: Guild[];
  total: number;
}

export interface BroadcastRequest {
  message: string;
}

export interface BroadcastResult {
  sent: number;
  failed: number;
  total: number;
}

export type ListUsersParams = {
  page?: number;
  limit?: number;
  search?: string;
};

export type UpdateTournamentStatusBodyStatus =
  (typeof UpdateTournamentStatusBodyStatus)[keyof typeof UpdateTournamentStatusBodyStatus];

export const UpdateTournamentStatusBodyStatus = {
  active: "active",
  ended: "ended",
  pending: "pending",
} as const;

export type UpdateTournamentStatusBody = {
  status: UpdateTournamentStatusBodyStatus;
};
