/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Anime RPG Bot Admin API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  Ad,
  AddMarketItemRequest,
  AdsListResponse,
  BroadcastRequest,
  BroadcastResult,
  Card,
  CardsListResponse,
  Character,
  CharactersListResponse,
  CreateAdRequest,
  CreateCardRequest,
  CreateCharacterRequest,
  CreateTournamentRequest,
  DashboardStats,
  GroupsListResponse,
  GuildsListResponse,
  HealthStatus,
  ListUsersParams,
  MarketItem,
  MarketListResponse,
  SuccessResponse,
  Tournament,
  TournamentsListResponse,
  UpdateTournamentStatusBody,
  UpdateUserRequest,
  User,
  UsersListResponse,
} from "./api.schemas";

import { customFetch } from "../custom-fetch";
import type { ErrorType, BodyType } from "../custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get dashboard statistics
 */
export const getGetDashboardStatsUrl = () => {
  return `/api/stats`;
};

export const getDashboardStats = async (
  options?: RequestInit,
): Promise<DashboardStats> => {
  return customFetch<DashboardStats>(getGetDashboardStatsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetDashboardStatsQueryKey = () => {
  return [`/api/stats`] as const;
};

export const getGetDashboardStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDashboardStatsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDashboardStats>>
  > = ({ signal }) => getDashboardStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetDashboardStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardStats>>
>;
export type GetDashboardStatsQueryError = ErrorType<unknown>;

/**
 * @summary Get dashboard statistics
 */

export function useGetDashboardStats<
  TData = Awaited<ReturnType<typeof getDashboardStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetDashboardStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List all users
 */
export const getListUsersUrl = (params?: ListUsersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/users?${stringifiedParams}`
    : `/api/users`;
};

export const listUsers = async (
  params?: ListUsersParams,
  options?: RequestInit,
): Promise<UsersListResponse> => {
  return customFetch<UsersListResponse>(getListUsersUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListUsersQueryKey = (params?: ListUsersParams) => {
  return [`/api/users`, ...(params ? [params] : [])] as const;
};

export const getListUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof listUsers>>,
  TError = ErrorType<unknown>,
>(
  params?: ListUsersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listUsers>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListUsersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsers>>> = ({
    signal,
  }) => listUsers(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listUsers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof listUsers>>
>;
export type ListUsersQueryError = ErrorType<unknown>;

/**
 * @summary List all users
 */

export function useListUsers<
  TData = Awaited<ReturnType<typeof listUsers>>,
  TError = ErrorType<unknown>,
>(
  params?: ListUsersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listUsers>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListUsersQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get user by ID
 */
export const getGetUserUrl = (userId: number) => {
  return `/api/users/${userId}`;
};

export const getUser = async (
  userId: number,
  options?: RequestInit,
): Promise<User> => {
  return customFetch<User>(getGetUserUrl(userId), {
    ...options,
    method: "GET",
  });
};

export const getGetUserQueryKey = (userId: number) => {
  return [`/api/users/${userId}`] as const;
};

export const getGetUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = ErrorType<unknown>,
>(
  userId: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserQueryKey(userId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({
    signal,
  }) => getUser(userId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!userId,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUser>>
>;
export type GetUserQueryError = ErrorType<unknown>;

/**
 * @summary Get user by ID
 */

export function useGetUser<
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = ErrorType<unknown>,
>(
  userId: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUserQueryOptions(userId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update user
 */
export const getUpdateUserUrl = (userId: number) => {
  return `/api/users/${userId}`;
};

export const updateUser = async (
  userId: number,
  updateUserRequest: UpdateUserRequest,
  options?: RequestInit,
): Promise<User> => {
  return customFetch<User>(getUpdateUserUrl(userId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateUserRequest),
  });
};

export const getUpdateUserMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    { userId: number; data: BodyType<UpdateUserRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUser>>,
  TError,
  { userId: number; data: BodyType<UpdateUserRequest> },
  TContext
> => {
  const mutationKey = ["updateUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUser>>,
    { userId: number; data: BodyType<UpdateUserRequest> }
  > = (props) => {
    const { userId, data } = props ?? {};

    return updateUser(userId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUser>>
>;
export type UpdateUserMutationBody = BodyType<UpdateUserRequest>;
export type UpdateUserMutationError = ErrorType<unknown>;

/**
 * @summary Update user
 */
export const useUpdateUser = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    { userId: number; data: BodyType<UpdateUserRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateUser>>,
  TError,
  { userId: number; data: BodyType<UpdateUserRequest> },
  TContext
> => {
  return useMutation(getUpdateUserMutationOptions(options));
};

/**
 * @summary List all groups
 */
export const getListGroupsUrl = () => {
  return `/api/groups`;
};

export const listGroups = async (
  options?: RequestInit,
): Promise<GroupsListResponse> => {
  return customFetch<GroupsListResponse>(getListGroupsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListGroupsQueryKey = () => {
  return [`/api/groups`] as const;
};

export const getListGroupsQueryOptions = <
  TData = Awaited<ReturnType<typeof listGroups>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listGroups>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListGroupsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listGroups>>> = ({
    signal,
  }) => listGroups({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listGroups>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListGroupsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listGroups>>
>;
export type ListGroupsQueryError = ErrorType<unknown>;

/**
 * @summary List all groups
 */

export function useListGroups<
  TData = Awaited<ReturnType<typeof listGroups>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listGroups>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListGroupsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete a group
 */
export const getDeleteGroupUrl = (groupId: number) => {
  return `/api/groups/${groupId}`;
};

export const deleteGroup = async (
  groupId: number,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getDeleteGroupUrl(groupId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteGroupMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteGroup>>,
    TError,
    { groupId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteGroup>>,
  TError,
  { groupId: number },
  TContext
> => {
  const mutationKey = ["deleteGroup"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteGroup>>,
    { groupId: number }
  > = (props) => {
    const { groupId } = props ?? {};

    return deleteGroup(groupId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteGroup>>
>;

export type DeleteGroupMutationError = ErrorType<unknown>;

/**
 * @summary Delete a group
 */
export const useDeleteGroup = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteGroup>>,
    TError,
    { groupId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteGroup>>,
  TError,
  { groupId: number },
  TContext
> => {
  return useMutation(getDeleteGroupMutationOptions(options));
};

/**
 * @summary List all characters
 */
export const getListCharactersUrl = () => {
  return `/api/characters`;
};

export const listCharacters = async (
  options?: RequestInit,
): Promise<CharactersListResponse> => {
  return customFetch<CharactersListResponse>(getListCharactersUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListCharactersQueryKey = () => {
  return [`/api/characters`] as const;
};

export const getListCharactersQueryOptions = <
  TData = Awaited<ReturnType<typeof listCharacters>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listCharacters>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListCharactersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listCharacters>>> = ({
    signal,
  }) => listCharacters({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listCharacters>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListCharactersQueryResult = NonNullable<
  Awaited<ReturnType<typeof listCharacters>>
>;
export type ListCharactersQueryError = ErrorType<unknown>;

/**
 * @summary List all characters
 */

export function useListCharacters<
  TData = Awaited<ReturnType<typeof listCharacters>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listCharacters>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListCharactersQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a character (multipart with image)
 */
export const getCreateCharacterUrl = () => {
  return `/api/characters`;
};

export const createCharacter = async (
  createCharacterRequest: CreateCharacterRequest,
  options?: RequestInit,
): Promise<Character> => {
  const formData = new FormData();
  formData.append(`name`, createCharacterRequest.name);
  formData.append(`rarity`, createCharacterRequest.rarity);
  formData.append(`power`, createCharacterRequest.power.toString());
  formData.append(`kills`, createCharacterRequest.kills.toString());
  if (createCharacterRequest.skills !== undefined) {
    formData.append(`skills`, createCharacterRequest.skills);
  }
  formData.append(`price`, createCharacterRequest.price.toString());
  if (createCharacterRequest.image !== undefined) {
    formData.append(`image`, createCharacterRequest.image);
  }

  return customFetch<Character>(getCreateCharacterUrl(), {
    ...options,
    method: "POST",
    body: formData,
  });
};

export const getCreateCharacterMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCharacter>>,
    TError,
    { data: BodyType<CreateCharacterRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCharacter>>,
  TError,
  { data: BodyType<CreateCharacterRequest> },
  TContext
> => {
  const mutationKey = ["createCharacter"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCharacter>>,
    { data: BodyType<CreateCharacterRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createCharacter(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCharacterMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCharacter>>
>;
export type CreateCharacterMutationBody = BodyType<CreateCharacterRequest>;
export type CreateCharacterMutationError = ErrorType<unknown>;

/**
 * @summary Create a character (multipart with image)
 */
export const useCreateCharacter = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCharacter>>,
    TError,
    { data: BodyType<CreateCharacterRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createCharacter>>,
  TError,
  { data: BodyType<CreateCharacterRequest> },
  TContext
> => {
  return useMutation(getCreateCharacterMutationOptions(options));
};

/**
 * @summary Get character by ID
 */
export const getGetCharacterUrl = (characterId: number) => {
  return `/api/characters/${characterId}`;
};

export const getCharacter = async (
  characterId: number,
  options?: RequestInit,
): Promise<Character> => {
  return customFetch<Character>(getGetCharacterUrl(characterId), {
    ...options,
    method: "GET",
  });
};

export const getGetCharacterQueryKey = (characterId: number) => {
  return [`/api/characters/${characterId}`] as const;
};

export const getGetCharacterQueryOptions = <
  TData = Awaited<ReturnType<typeof getCharacter>>,
  TError = ErrorType<unknown>,
>(
  characterId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getCharacter>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCharacterQueryKey(characterId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCharacter>>> = ({
    signal,
  }) => getCharacter(characterId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!characterId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCharacter>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCharacterQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCharacter>>
>;
export type GetCharacterQueryError = ErrorType<unknown>;

/**
 * @summary Get character by ID
 */

export function useGetCharacter<
  TData = Awaited<ReturnType<typeof getCharacter>>,
  TError = ErrorType<unknown>,
>(
  characterId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getCharacter>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCharacterQueryOptions(characterId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update character
 */
export const getUpdateCharacterUrl = (characterId: number) => {
  return `/api/characters/${characterId}`;
};

export const updateCharacter = async (
  characterId: number,
  createCharacterRequest: CreateCharacterRequest,
  options?: RequestInit,
): Promise<Character> => {
  const formData = new FormData();
  formData.append(`name`, createCharacterRequest.name);
  formData.append(`rarity`, createCharacterRequest.rarity);
  formData.append(`power`, createCharacterRequest.power.toString());
  formData.append(`kills`, createCharacterRequest.kills.toString());
  if (createCharacterRequest.skills !== undefined) {
    formData.append(`skills`, createCharacterRequest.skills);
  }
  formData.append(`price`, createCharacterRequest.price.toString());
  if (createCharacterRequest.image !== undefined) {
    formData.append(`image`, createCharacterRequest.image);
  }

  return customFetch<Character>(getUpdateCharacterUrl(characterId), {
    ...options,
    method: "PUT",
    body: formData,
  });
};

export const getUpdateCharacterMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCharacter>>,
    TError,
    { characterId: number; data: BodyType<CreateCharacterRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCharacter>>,
  TError,
  { characterId: number; data: BodyType<CreateCharacterRequest> },
  TContext
> => {
  const mutationKey = ["updateCharacter"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCharacter>>,
    { characterId: number; data: BodyType<CreateCharacterRequest> }
  > = (props) => {
    const { characterId, data } = props ?? {};

    return updateCharacter(characterId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCharacterMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCharacter>>
>;
export type UpdateCharacterMutationBody = BodyType<CreateCharacterRequest>;
export type UpdateCharacterMutationError = ErrorType<unknown>;

/**
 * @summary Update character
 */
export const useUpdateCharacter = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCharacter>>,
    TError,
    { characterId: number; data: BodyType<CreateCharacterRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateCharacter>>,
  TError,
  { characterId: number; data: BodyType<CreateCharacterRequest> },
  TContext
> => {
  return useMutation(getUpdateCharacterMutationOptions(options));
};

/**
 * @summary Delete character
 */
export const getDeleteCharacterUrl = (characterId: number) => {
  return `/api/characters/${characterId}`;
};

export const deleteCharacter = async (
  characterId: number,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getDeleteCharacterUrl(characterId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteCharacterMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCharacter>>,
    TError,
    { characterId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCharacter>>,
  TError,
  { characterId: number },
  TContext
> => {
  const mutationKey = ["deleteCharacter"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCharacter>>,
    { characterId: number }
  > = (props) => {
    const { characterId } = props ?? {};

    return deleteCharacter(characterId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCharacterMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCharacter>>
>;

export type DeleteCharacterMutationError = ErrorType<unknown>;

/**
 * @summary Delete character
 */
export const useDeleteCharacter = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCharacter>>,
    TError,
    { characterId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteCharacter>>,
  TError,
  { characterId: number },
  TContext
> => {
  return useMutation(getDeleteCharacterMutationOptions(options));
};

/**
 * @summary List all cards
 */
export const getListCardsUrl = () => {
  return `/api/cards`;
};

export const listCards = async (
  options?: RequestInit,
): Promise<CardsListResponse> => {
  return customFetch<CardsListResponse>(getListCardsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListCardsQueryKey = () => {
  return [`/api/cards`] as const;
};

export const getListCardsQueryOptions = <
  TData = Awaited<ReturnType<typeof listCards>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof listCards>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListCardsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listCards>>> = ({
    signal,
  }) => listCards({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listCards>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListCardsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listCards>>
>;
export type ListCardsQueryError = ErrorType<unknown>;

/**
 * @summary List all cards
 */

export function useListCards<
  TData = Awaited<ReturnType<typeof listCards>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof listCards>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListCardsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a card (multipart with image)
 */
export const getCreateCardUrl = () => {
  return `/api/cards`;
};

export const createCard = async (
  createCardRequest: CreateCardRequest,
  options?: RequestInit,
): Promise<Card> => {
  const formData = new FormData();
  formData.append(`name`, createCardRequest.name);
  formData.append(`rarity`, createCardRequest.rarity);
  formData.append(`power`, createCardRequest.power.toString());
  if (createCardRequest.skills !== undefined) {
    formData.append(`skills`, createCardRequest.skills);
  }
  formData.append(`price`, createCardRequest.price.toString());
  if (createCardRequest.image !== undefined) {
    formData.append(`image`, createCardRequest.image);
  }

  return customFetch<Card>(getCreateCardUrl(), {
    ...options,
    method: "POST",
    body: formData,
  });
};

export const getCreateCardMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCard>>,
    TError,
    { data: BodyType<CreateCardRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCard>>,
  TError,
  { data: BodyType<CreateCardRequest> },
  TContext
> => {
  const mutationKey = ["createCard"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCard>>,
    { data: BodyType<CreateCardRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createCard(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCardMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCard>>
>;
export type CreateCardMutationBody = BodyType<CreateCardRequest>;
export type CreateCardMutationError = ErrorType<unknown>;

/**
 * @summary Create a card (multipart with image)
 */
export const useCreateCard = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCard>>,
    TError,
    { data: BodyType<CreateCardRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createCard>>,
  TError,
  { data: BodyType<CreateCardRequest> },
  TContext
> => {
  return useMutation(getCreateCardMutationOptions(options));
};

/**
 * @summary Get card by ID
 */
export const getGetCardUrl = (cardId: number) => {
  return `/api/cards/${cardId}`;
};

export const getCard = async (
  cardId: number,
  options?: RequestInit,
): Promise<Card> => {
  return customFetch<Card>(getGetCardUrl(cardId), {
    ...options,
    method: "GET",
  });
};

export const getGetCardQueryKey = (cardId: number) => {
  return [`/api/cards/${cardId}`] as const;
};

export const getGetCardQueryOptions = <
  TData = Awaited<ReturnType<typeof getCard>>,
  TError = ErrorType<unknown>,
>(
  cardId: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getCard>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCardQueryKey(cardId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCard>>> = ({
    signal,
  }) => getCard(cardId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!cardId,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getCard>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetCardQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCard>>
>;
export type GetCardQueryError = ErrorType<unknown>;

/**
 * @summary Get card by ID
 */

export function useGetCard<
  TData = Awaited<ReturnType<typeof getCard>>,
  TError = ErrorType<unknown>,
>(
  cardId: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getCard>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCardQueryOptions(cardId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update card
 */
export const getUpdateCardUrl = (cardId: number) => {
  return `/api/cards/${cardId}`;
};

export const updateCard = async (
  cardId: number,
  createCardRequest: CreateCardRequest,
  options?: RequestInit,
): Promise<Card> => {
  const formData = new FormData();
  formData.append(`name`, createCardRequest.name);
  formData.append(`rarity`, createCardRequest.rarity);
  formData.append(`power`, createCardRequest.power.toString());
  if (createCardRequest.skills !== undefined) {
    formData.append(`skills`, createCardRequest.skills);
  }
  formData.append(`price`, createCardRequest.price.toString());
  if (createCardRequest.image !== undefined) {
    formData.append(`image`, createCardRequest.image);
  }

  return customFetch<Card>(getUpdateCardUrl(cardId), {
    ...options,
    method: "PUT",
    body: formData,
  });
};

export const getUpdateCardMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCard>>,
    TError,
    { cardId: number; data: BodyType<CreateCardRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCard>>,
  TError,
  { cardId: number; data: BodyType<CreateCardRequest> },
  TContext
> => {
  const mutationKey = ["updateCard"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCard>>,
    { cardId: number; data: BodyType<CreateCardRequest> }
  > = (props) => {
    const { cardId, data } = props ?? {};

    return updateCard(cardId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCardMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCard>>
>;
export type UpdateCardMutationBody = BodyType<CreateCardRequest>;
export type UpdateCardMutationError = ErrorType<unknown>;

/**
 * @summary Update card
 */
export const useUpdateCard = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCard>>,
    TError,
    { cardId: number; data: BodyType<CreateCardRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateCard>>,
  TError,
  { cardId: number; data: BodyType<CreateCardRequest> },
  TContext
> => {
  return useMutation(getUpdateCardMutationOptions(options));
};

/**
 * @summary Delete card
 */
export const getDeleteCardUrl = (cardId: number) => {
  return `/api/cards/${cardId}`;
};

export const deleteCard = async (
  cardId: number,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getDeleteCardUrl(cardId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteCardMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCard>>,
    TError,
    { cardId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCard>>,
  TError,
  { cardId: number },
  TContext
> => {
  const mutationKey = ["deleteCard"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCard>>,
    { cardId: number }
  > = (props) => {
    const { cardId } = props ?? {};

    return deleteCard(cardId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCardMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCard>>
>;

export type DeleteCardMutationError = ErrorType<unknown>;

/**
 * @summary Delete card
 */
export const useDeleteCard = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCard>>,
    TError,
    { cardId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteCard>>,
  TError,
  { cardId: number },
  TContext
> => {
  return useMutation(getDeleteCardMutationOptions(options));
};

/**
 * @summary List all ads
 */
export const getListAdsUrl = () => {
  return `/api/ads`;
};

export const listAds = async (
  options?: RequestInit,
): Promise<AdsListResponse> => {
  return customFetch<AdsListResponse>(getListAdsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListAdsQueryKey = () => {
  return [`/api/ads`] as const;
};

export const getListAdsQueryOptions = <
  TData = Awaited<ReturnType<typeof listAds>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof listAds>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListAdsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAds>>> = ({
    signal,
  }) => listAds({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAds>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListAdsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAds>>
>;
export type ListAdsQueryError = ErrorType<unknown>;

/**
 * @summary List all ads
 */

export function useListAds<
  TData = Awaited<ReturnType<typeof listAds>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof listAds>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListAdsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create an ad
 */
export const getCreateAdUrl = () => {
  return `/api/ads`;
};

export const createAd = async (
  createAdRequest: CreateAdRequest,
  options?: RequestInit,
): Promise<Ad> => {
  return customFetch<Ad>(getCreateAdUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createAdRequest),
  });
};

export const getCreateAdMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAd>>,
    TError,
    { data: BodyType<CreateAdRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createAd>>,
  TError,
  { data: BodyType<CreateAdRequest> },
  TContext
> => {
  const mutationKey = ["createAd"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createAd>>,
    { data: BodyType<CreateAdRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createAd(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateAdMutationResult = NonNullable<
  Awaited<ReturnType<typeof createAd>>
>;
export type CreateAdMutationBody = BodyType<CreateAdRequest>;
export type CreateAdMutationError = ErrorType<unknown>;

/**
 * @summary Create an ad
 */
export const useCreateAd = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAd>>,
    TError,
    { data: BodyType<CreateAdRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createAd>>,
  TError,
  { data: BodyType<CreateAdRequest> },
  TContext
> => {
  return useMutation(getCreateAdMutationOptions(options));
};

/**
 * @summary Update ad
 */
export const getUpdateAdUrl = (adId: number) => {
  return `/api/ads/${adId}`;
};

export const updateAd = async (
  adId: number,
  createAdRequest: CreateAdRequest,
  options?: RequestInit,
): Promise<Ad> => {
  return customFetch<Ad>(getUpdateAdUrl(adId), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createAdRequest),
  });
};

export const getUpdateAdMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAd>>,
    TError,
    { adId: number; data: BodyType<CreateAdRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAd>>,
  TError,
  { adId: number; data: BodyType<CreateAdRequest> },
  TContext
> => {
  const mutationKey = ["updateAd"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAd>>,
    { adId: number; data: BodyType<CreateAdRequest> }
  > = (props) => {
    const { adId, data } = props ?? {};

    return updateAd(adId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAdMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAd>>
>;
export type UpdateAdMutationBody = BodyType<CreateAdRequest>;
export type UpdateAdMutationError = ErrorType<unknown>;

/**
 * @summary Update ad
 */
export const useUpdateAd = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAd>>,
    TError,
    { adId: number; data: BodyType<CreateAdRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateAd>>,
  TError,
  { adId: number; data: BodyType<CreateAdRequest> },
  TContext
> => {
  return useMutation(getUpdateAdMutationOptions(options));
};

/**
 * @summary Delete ad
 */
export const getDeleteAdUrl = (adId: number) => {
  return `/api/ads/${adId}`;
};

export const deleteAd = async (
  adId: number,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getDeleteAdUrl(adId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteAdMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAd>>,
    TError,
    { adId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAd>>,
  TError,
  { adId: number },
  TContext
> => {
  const mutationKey = ["deleteAd"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAd>>,
    { adId: number }
  > = (props) => {
    const { adId } = props ?? {};

    return deleteAd(adId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAd>>
>;

export type DeleteAdMutationError = ErrorType<unknown>;

/**
 * @summary Delete ad
 */
export const useDeleteAd = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAd>>,
    TError,
    { adId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteAd>>,
  TError,
  { adId: number },
  TContext
> => {
  return useMutation(getDeleteAdMutationOptions(options));
};

/**
 * @summary Toggle ad status
 */
export const getToggleAdUrl = (adId: number) => {
  return `/api/ads/${adId}/toggle`;
};

export const toggleAd = async (
  adId: number,
  options?: RequestInit,
): Promise<Ad> => {
  return customFetch<Ad>(getToggleAdUrl(adId), {
    ...options,
    method: "PATCH",
  });
};

export const getToggleAdMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof toggleAd>>,
    TError,
    { adId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof toggleAd>>,
  TError,
  { adId: number },
  TContext
> => {
  const mutationKey = ["toggleAd"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof toggleAd>>,
    { adId: number }
  > = (props) => {
    const { adId } = props ?? {};

    return toggleAd(adId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ToggleAdMutationResult = NonNullable<
  Awaited<ReturnType<typeof toggleAd>>
>;

export type ToggleAdMutationError = ErrorType<unknown>;

/**
 * @summary Toggle ad status
 */
export const useToggleAd = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof toggleAd>>,
    TError,
    { adId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof toggleAd>>,
  TError,
  { adId: number },
  TContext
> => {
  return useMutation(getToggleAdMutationOptions(options));
};

/**
 * @summary List all tournaments
 */
export const getListTournamentsUrl = () => {
  return `/api/tournaments`;
};

export const listTournaments = async (
  options?: RequestInit,
): Promise<TournamentsListResponse> => {
  return customFetch<TournamentsListResponse>(getListTournamentsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListTournamentsQueryKey = () => {
  return [`/api/tournaments`] as const;
};

export const getListTournamentsQueryOptions = <
  TData = Awaited<ReturnType<typeof listTournaments>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listTournaments>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTournamentsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listTournaments>>> = ({
    signal,
  }) => listTournaments({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listTournaments>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListTournamentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listTournaments>>
>;
export type ListTournamentsQueryError = ErrorType<unknown>;

/**
 * @summary List all tournaments
 */

export function useListTournaments<
  TData = Awaited<ReturnType<typeof listTournaments>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listTournaments>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListTournamentsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a tournament
 */
export const getCreateTournamentUrl = () => {
  return `/api/tournaments`;
};

export const createTournament = async (
  createTournamentRequest: CreateTournamentRequest,
  options?: RequestInit,
): Promise<Tournament> => {
  return customFetch<Tournament>(getCreateTournamentUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createTournamentRequest),
  });
};

export const getCreateTournamentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTournament>>,
    TError,
    { data: BodyType<CreateTournamentRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTournament>>,
  TError,
  { data: BodyType<CreateTournamentRequest> },
  TContext
> => {
  const mutationKey = ["createTournament"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTournament>>,
    { data: BodyType<CreateTournamentRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createTournament(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTournamentMutationResult = NonNullable<
  Awaited<ReturnType<typeof createTournament>>
>;
export type CreateTournamentMutationBody = BodyType<CreateTournamentRequest>;
export type CreateTournamentMutationError = ErrorType<unknown>;

/**
 * @summary Create a tournament
 */
export const useCreateTournament = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTournament>>,
    TError,
    { data: BodyType<CreateTournamentRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createTournament>>,
  TError,
  { data: BodyType<CreateTournamentRequest> },
  TContext
> => {
  return useMutation(getCreateTournamentMutationOptions(options));
};

/**
 * @summary Delete tournament
 */
export const getDeleteTournamentUrl = (tournamentId: number) => {
  return `/api/tournaments/${tournamentId}`;
};

export const deleteTournament = async (
  tournamentId: number,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getDeleteTournamentUrl(tournamentId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteTournamentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTournament>>,
    TError,
    { tournamentId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTournament>>,
  TError,
  { tournamentId: number },
  TContext
> => {
  const mutationKey = ["deleteTournament"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteTournament>>,
    { tournamentId: number }
  > = (props) => {
    const { tournamentId } = props ?? {};

    return deleteTournament(tournamentId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteTournamentMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteTournament>>
>;

export type DeleteTournamentMutationError = ErrorType<unknown>;

/**
 * @summary Delete tournament
 */
export const useDeleteTournament = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTournament>>,
    TError,
    { tournamentId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteTournament>>,
  TError,
  { tournamentId: number },
  TContext
> => {
  return useMutation(getDeleteTournamentMutationOptions(options));
};

/**
 * @summary Update tournament status
 */
export const getUpdateTournamentStatusUrl = (tournamentId: number) => {
  return `/api/tournaments/${tournamentId}`;
};

export const updateTournamentStatus = async (
  tournamentId: number,
  updateTournamentStatusBody: UpdateTournamentStatusBody,
  options?: RequestInit,
): Promise<Tournament> => {
  return customFetch<Tournament>(getUpdateTournamentStatusUrl(tournamentId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateTournamentStatusBody),
  });
};

export const getUpdateTournamentStatusMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTournamentStatus>>,
    TError,
    { tournamentId: number; data: BodyType<UpdateTournamentStatusBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateTournamentStatus>>,
  TError,
  { tournamentId: number; data: BodyType<UpdateTournamentStatusBody> },
  TContext
> => {
  const mutationKey = ["updateTournamentStatus"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateTournamentStatus>>,
    { tournamentId: number; data: BodyType<UpdateTournamentStatusBody> }
  > = (props) => {
    const { tournamentId, data } = props ?? {};

    return updateTournamentStatus(tournamentId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateTournamentStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateTournamentStatus>>
>;
export type UpdateTournamentStatusMutationBody =
  BodyType<UpdateTournamentStatusBody>;
export type UpdateTournamentStatusMutationError = ErrorType<unknown>;

/**
 * @summary Update tournament status
 */
export const useUpdateTournamentStatus = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTournamentStatus>>,
    TError,
    { tournamentId: number; data: BodyType<UpdateTournamentStatusBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateTournamentStatus>>,
  TError,
  { tournamentId: number; data: BodyType<UpdateTournamentStatusBody> },
  TContext
> => {
  return useMutation(getUpdateTournamentStatusMutationOptions(options));
};

/**
 * @summary List market items
 */
export const getListMarketItemsUrl = () => {
  return `/api/market`;
};

export const listMarketItems = async (
  options?: RequestInit,
): Promise<MarketListResponse> => {
  return customFetch<MarketListResponse>(getListMarketItemsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListMarketItemsQueryKey = () => {
  return [`/api/market`] as const;
};

export const getListMarketItemsQueryOptions = <
  TData = Awaited<ReturnType<typeof listMarketItems>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listMarketItems>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListMarketItemsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMarketItems>>> = ({
    signal,
  }) => listMarketItems({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listMarketItems>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListMarketItemsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMarketItems>>
>;
export type ListMarketItemsQueryError = ErrorType<unknown>;

/**
 * @summary List market items
 */

export function useListMarketItems<
  TData = Awaited<ReturnType<typeof listMarketItems>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listMarketItems>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListMarketItemsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Add item to market
 */
export const getAddMarketItemUrl = () => {
  return `/api/market`;
};

export const addMarketItem = async (
  addMarketItemRequest: AddMarketItemRequest,
  options?: RequestInit,
): Promise<MarketItem> => {
  return customFetch<MarketItem>(getAddMarketItemUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(addMarketItemRequest),
  });
};

export const getAddMarketItemMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addMarketItem>>,
    TError,
    { data: BodyType<AddMarketItemRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addMarketItem>>,
  TError,
  { data: BodyType<AddMarketItemRequest> },
  TContext
> => {
  const mutationKey = ["addMarketItem"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addMarketItem>>,
    { data: BodyType<AddMarketItemRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return addMarketItem(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddMarketItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof addMarketItem>>
>;
export type AddMarketItemMutationBody = BodyType<AddMarketItemRequest>;
export type AddMarketItemMutationError = ErrorType<unknown>;

/**
 * @summary Add item to market
 */
export const useAddMarketItem = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addMarketItem>>,
    TError,
    { data: BodyType<AddMarketItemRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof addMarketItem>>,
  TError,
  { data: BodyType<AddMarketItemRequest> },
  TContext
> => {
  return useMutation(getAddMarketItemMutationOptions(options));
};

/**
 * @summary Remove market item
 */
export const getRemoveMarketItemUrl = (marketId: number) => {
  return `/api/market/${marketId}`;
};

export const removeMarketItem = async (
  marketId: number,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getRemoveMarketItemUrl(marketId), {
    ...options,
    method: "DELETE",
  });
};

export const getRemoveMarketItemMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeMarketItem>>,
    TError,
    { marketId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeMarketItem>>,
  TError,
  { marketId: number },
  TContext
> => {
  const mutationKey = ["removeMarketItem"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeMarketItem>>,
    { marketId: number }
  > = (props) => {
    const { marketId } = props ?? {};

    return removeMarketItem(marketId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveMarketItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeMarketItem>>
>;

export type RemoveMarketItemMutationError = ErrorType<unknown>;

/**
 * @summary Remove market item
 */
export const useRemoveMarketItem = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeMarketItem>>,
    TError,
    { marketId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof removeMarketItem>>,
  TError,
  { marketId: number },
  TContext
> => {
  return useMutation(getRemoveMarketItemMutationOptions(options));
};

/**
 * @summary List all guilds
 */
export const getListGuildsUrl = () => {
  return `/api/guilds`;
};

export const listGuilds = async (
  options?: RequestInit,
): Promise<GuildsListResponse> => {
  return customFetch<GuildsListResponse>(getListGuildsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListGuildsQueryKey = () => {
  return [`/api/guilds`] as const;
};

export const getListGuildsQueryOptions = <
  TData = Awaited<ReturnType<typeof listGuilds>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listGuilds>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListGuildsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listGuilds>>> = ({
    signal,
  }) => listGuilds({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listGuilds>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListGuildsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listGuilds>>
>;
export type ListGuildsQueryError = ErrorType<unknown>;

/**
 * @summary List all guilds
 */

export function useListGuilds<
  TData = Awaited<ReturnType<typeof listGuilds>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listGuilds>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListGuildsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Send broadcast to all groups
 */
export const getSendBroadcastUrl = () => {
  return `/api/broadcast`;
};

export const sendBroadcast = async (
  broadcastRequest: BroadcastRequest,
  options?: RequestInit,
): Promise<BroadcastResult> => {
  return customFetch<BroadcastResult>(getSendBroadcastUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(broadcastRequest),
  });
};

export const getSendBroadcastMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendBroadcast>>,
    TError,
    { data: BodyType<BroadcastRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendBroadcast>>,
  TError,
  { data: BodyType<BroadcastRequest> },
  TContext
> => {
  const mutationKey = ["sendBroadcast"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendBroadcast>>,
    { data: BodyType<BroadcastRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return sendBroadcast(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SendBroadcastMutationResult = NonNullable<
  Awaited<ReturnType<typeof sendBroadcast>>
>;
export type SendBroadcastMutationBody = BodyType<BroadcastRequest>;
export type SendBroadcastMutationError = ErrorType<unknown>;

/**
 * @summary Send broadcast to all groups
 */
export const useSendBroadcast = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendBroadcast>>,
    TError,
    { data: BodyType<BroadcastRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof sendBroadcast>>,
  TError,
  { data: BodyType<BroadcastRequest> },
  TContext
> => {
  return useMutation(getSendBroadcastMutationOptions(options));
};
