/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Anime RPG Bot Admin API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Get dashboard statistics
 */
export const GetDashboardStatsResponse = zod.object({
  totalUsers: zod.number(),
  totalGroups: zod.number(),
  totalCoins: zod.number(),
  activeAds: zod.number(),
  activeTournaments: zod.number(),
  totalCharacters: zod.number(),
  totalCards: zod.number(),
  premiumUsers: zod.number(),
});

/**
 * @summary List all users
 */
export const listUsersQueryPageDefault = 1;
export const listUsersQueryLimitDefault = 50;

export const ListUsersQueryParams = zod.object({
  page: zod.coerce.number().default(listUsersQueryPageDefault),
  limit: zod.coerce.number().default(listUsersQueryLimitDefault),
  search: zod.coerce.string().optional(),
});

export const ListUsersResponse = zod.object({
  users: zod.array(
    zod.object({
      userId: zod.number(),
      username: zod.string().nullish(),
      firstName: zod.string().nullish(),
      coins: zod.number(),
      bank: zod.number(),
      xp: zod.number(),
      level: zod.number(),
      premiumUntil: zod.string().nullish(),
      joinedAt: zod.string(),
      charactersCount: zod.number(),
      cardsCount: zod.number(),
    }),
  ),
  total: zod.number(),
  page: zod.number(),
  limit: zod.number(),
});

/**
 * @summary Get user by ID
 */
export const GetUserParams = zod.object({
  userId: zod.coerce.number(),
});

export const GetUserResponse = zod.object({
  userId: zod.number(),
  username: zod.string().nullish(),
  firstName: zod.string().nullish(),
  coins: zod.number(),
  bank: zod.number(),
  xp: zod.number(),
  level: zod.number(),
  premiumUntil: zod.string().nullish(),
  joinedAt: zod.string(),
  charactersCount: zod.number(),
  cardsCount: zod.number(),
});

/**
 * @summary Update user
 */
export const UpdateUserParams = zod.object({
  userId: zod.coerce.number(),
});

export const UpdateUserBody = zod.object({
  coins: zod.number().optional(),
  bank: zod.number().optional(),
  xp: zod.number().optional(),
  level: zod.number().optional(),
  premiumUntil: zod.string().nullish(),
});

export const UpdateUserResponse = zod.object({
  userId: zod.number(),
  username: zod.string().nullish(),
  firstName: zod.string().nullish(),
  coins: zod.number(),
  bank: zod.number(),
  xp: zod.number(),
  level: zod.number(),
  premiumUntil: zod.string().nullish(),
  joinedAt: zod.string(),
  charactersCount: zod.number(),
  cardsCount: zod.number(),
});

/**
 * @summary List all groups
 */
export const ListGroupsResponse = zod.object({
  groups: zod.array(
    zod.object({
      id: zod.number(),
      chatId: zod.string(),
      groupName: zod.string().nullish(),
      addedAt: zod.string(),
    }),
  ),
  total: zod.number(),
});

/**
 * @summary Delete a group
 */
export const DeleteGroupParams = zod.object({
  groupId: zod.coerce.number(),
});

export const DeleteGroupResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
});

/**
 * @summary List all characters
 */
export const ListCharactersResponse = zod.object({
  characters: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      rarity: zod.string(),
      power: zod.number(),
      kills: zod.number(),
      skills: zod.string().nullish(),
      price: zod.number(),
      imagePath: zod.string().nullish(),
    }),
  ),
  total: zod.number(),
});

/**
 * @summary Create a character (multipart with image)
 */
export const CreateCharacterBody = zod.object({
  name: zod.string(),
  rarity: zod.string(),
  power: zod.number(),
  kills: zod.number(),
  skills: zod.string().optional(),
  price: zod.number(),
  image: zod.instanceof(File).optional(),
});

/**
 * @summary Get character by ID
 */
export const GetCharacterParams = zod.object({
  characterId: zod.coerce.number(),
});

export const GetCharacterResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  rarity: zod.string(),
  power: zod.number(),
  kills: zod.number(),
  skills: zod.string().nullish(),
  price: zod.number(),
  imagePath: zod.string().nullish(),
});

/**
 * @summary Update character
 */
export const UpdateCharacterParams = zod.object({
  characterId: zod.coerce.number(),
});

export const UpdateCharacterBody = zod.object({
  name: zod.string(),
  rarity: zod.string(),
  power: zod.number(),
  kills: zod.number(),
  skills: zod.string().optional(),
  price: zod.number(),
  image: zod.instanceof(File).optional(),
});

export const UpdateCharacterResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  rarity: zod.string(),
  power: zod.number(),
  kills: zod.number(),
  skills: zod.string().nullish(),
  price: zod.number(),
  imagePath: zod.string().nullish(),
});

/**
 * @summary Delete character
 */
export const DeleteCharacterParams = zod.object({
  characterId: zod.coerce.number(),
});

export const DeleteCharacterResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
});

/**
 * @summary List all cards
 */
export const ListCardsResponse = zod.object({
  cards: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      rarity: zod.string(),
      power: zod.number(),
      skills: zod.string().nullish(),
      price: zod.number(),
      imagePath: zod.string().nullish(),
    }),
  ),
  total: zod.number(),
});

/**
 * @summary Create a card (multipart with image)
 */
export const CreateCardBody = zod.object({
  name: zod.string(),
  rarity: zod.string(),
  power: zod.number(),
  skills: zod.string().optional(),
  price: zod.number(),
  image: zod.instanceof(File).optional(),
});

/**
 * @summary Get card by ID
 */
export const GetCardParams = zod.object({
  cardId: zod.coerce.number(),
});

export const GetCardResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  rarity: zod.string(),
  power: zod.number(),
  skills: zod.string().nullish(),
  price: zod.number(),
  imagePath: zod.string().nullish(),
});

/**
 * @summary Update card
 */
export const UpdateCardParams = zod.object({
  cardId: zod.coerce.number(),
});

export const UpdateCardBody = zod.object({
  name: zod.string(),
  rarity: zod.string(),
  power: zod.number(),
  skills: zod.string().optional(),
  price: zod.number(),
  image: zod.instanceof(File).optional(),
});

export const UpdateCardResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  rarity: zod.string(),
  power: zod.number(),
  skills: zod.string().nullish(),
  price: zod.number(),
  imagePath: zod.string().nullish(),
});

/**
 * @summary Delete card
 */
export const DeleteCardParams = zod.object({
  cardId: zod.coerce.number(),
});

export const DeleteCardResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
});

/**
 * @summary List all ads
 */
export const ListAdsResponse = zod.object({
  ads: zod.array(
    zod.object({
      id: zod.number(),
      adText: zod.string(),
      status: zod.enum(["active", "inactive"]),
      createdAt: zod.string(),
    }),
  ),
  total: zod.number(),
});

/**
 * @summary Create an ad
 */
export const createAdBodyStatusDefault = `active`;

export const CreateAdBody = zod.object({
  adText: zod.string(),
  status: zod.enum(["active", "inactive"]).default(createAdBodyStatusDefault),
});

/**
 * @summary Update ad
 */
export const UpdateAdParams = zod.object({
  adId: zod.coerce.number(),
});

export const updateAdBodyStatusDefault = `active`;

export const UpdateAdBody = zod.object({
  adText: zod.string(),
  status: zod.enum(["active", "inactive"]).default(updateAdBodyStatusDefault),
});

export const UpdateAdResponse = zod.object({
  id: zod.number(),
  adText: zod.string(),
  status: zod.enum(["active", "inactive"]),
  createdAt: zod.string(),
});

/**
 * @summary Delete ad
 */
export const DeleteAdParams = zod.object({
  adId: zod.coerce.number(),
});

export const DeleteAdResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
});

/**
 * @summary Toggle ad status
 */
export const ToggleAdParams = zod.object({
  adId: zod.coerce.number(),
});

export const ToggleAdResponse = zod.object({
  id: zod.number(),
  adText: zod.string(),
  status: zod.enum(["active", "inactive"]),
  createdAt: zod.string(),
});

/**
 * @summary List all tournaments
 */
export const ListTournamentsResponse = zod.object({
  tournaments: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      status: zod.enum(["pending", "active", "ended"]),
      rewardType: zod.enum(["coins", "card", "character", "premium"]),
      rewardValue: zod.string(),
      participantCount: zod.number(),
      createdAt: zod.string(),
    }),
  ),
  total: zod.number(),
});

/**
 * @summary Create a tournament
 */
export const CreateTournamentBody = zod.object({
  name: zod.string(),
  rewardType: zod.enum(["coins", "card", "character", "premium"]),
  rewardValue: zod.string(),
});

/**
 * @summary Delete tournament
 */
export const DeleteTournamentParams = zod.object({
  tournamentId: zod.coerce.number(),
});

export const DeleteTournamentResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
});

/**
 * @summary Update tournament status
 */
export const UpdateTournamentStatusParams = zod.object({
  tournamentId: zod.coerce.number(),
});

export const UpdateTournamentStatusBody = zod.object({
  status: zod.enum(["active", "ended", "pending"]),
});

export const UpdateTournamentStatusResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  status: zod.enum(["pending", "active", "ended"]),
  rewardType: zod.enum(["coins", "card", "character", "premium"]),
  rewardValue: zod.string(),
  participantCount: zod.number(),
  createdAt: zod.string(),
});

/**
 * @summary List market items
 */
export const ListMarketItemsResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.number(),
      itemType: zod.enum(["character", "card"]),
      itemId: zod.number(),
      price: zod.number(),
      sellerId: zod.number().nullish(),
      itemName: zod.string().nullish(),
      itemRarity: zod.string().nullish(),
      itemPower: zod.number().nullish(),
      imagePath: zod.string().nullish(),
    }),
  ),
  total: zod.number(),
});

/**
 * @summary Add item to market
 */
export const AddMarketItemBody = zod.object({
  itemType: zod.enum(["character", "card"]),
  itemId: zod.number(),
  price: zod.number(),
});

/**
 * @summary Remove market item
 */
export const RemoveMarketItemParams = zod.object({
  marketId: zod.coerce.number(),
});

export const RemoveMarketItemResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
});

/**
 * @summary List all guilds
 */
export const ListGuildsResponse = zod.object({
  guilds: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      ownerId: zod.number(),
      level: zod.number(),
      coins: zod.number(),
      memberCount: zod.number(),
    }),
  ),
  total: zod.number(),
});

/**
 * @summary Send broadcast to all groups
 */
export const SendBroadcastBody = zod.object({
  message: zod.string(),
});

export const SendBroadcastResponse = zod.object({
  sent: zod.number(),
  failed: zod.number(),
  total: zod.number(),
});
