/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Anime RPG Bot Admin API
 * OpenAPI spec version: 0.1.0
 */

export interface Card {
  id: number;
  name: string;
  rarity: string;
  power: number;
  skills?: string | null;
  price: number;
  imagePath?: string | null;
}
