/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Anime RPG Bot Admin API
 * OpenAPI spec version: 0.1.0
 */

export interface CreateCardRequest {
  name: string;
  rarity: string;
  power: number;
  skills?: string;
  price: number;
  image?: Blob;
}
