/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Anime RPG Bot Admin API
 * OpenAPI spec version: 0.1.0
 */

export interface DashboardStats {
  totalUsers: number;
  totalGroups: number;
  totalCoins: number;
  activeAds: number;
  activeTournaments: number;
  totalCharacters: number;
  totalCards: number;
  premiumUsers: number;
}
