/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Anime RPG Bot Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { Group } from "./group";

export interface GroupsListResponse {
  groups: Group[];
  total: number;
}
