/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Anime RPG Bot Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { Guild } from "./guild";

export interface GuildsListResponse {
  guilds: Guild[];
  total: number;
}
