/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Anime RPG Bot Admin API
 * OpenAPI spec version: 0.1.0
 */

export type MarketItemItemType =
  (typeof MarketItemItemType)[keyof typeof MarketItemItemType];

export const MarketItemItemType = {
  character: "character",
  card: "card",
} as const;
