/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Anime RPG Bot Admin API
 * OpenAPI spec version: 0.1.0
 */
import type { TournamentRewardType } from "./tournamentRewardType";
import type { TournamentStatus } from "./tournamentStatus";

export interface Tournament {
  id: number;
  name: string;
  status: TournamentStatus;
  rewardType: TournamentRewardType;
  rewardValue: string;
  participantCount: number;
  createdAt: string;
}
