/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Anime RPG Bot Admin API
 * OpenAPI spec version: 0.1.0
 */

export type TournamentRewardType =
  (typeof TournamentRewardType)[keyof typeof TournamentRewardType];

export const TournamentRewardType = {
  coins: "coins",
  card: "card",
  character: "character",
  premium: "premium",
} as const;
