/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Anime RPG Bot Admin API
 * OpenAPI spec version: 0.1.0
 */

export type UpdateTournamentStatusBodyStatus =
  (typeof UpdateTournamentStatusBodyStatus)[keyof typeof UpdateTournamentStatusBodyStatus];

export const UpdateTournamentStatusBodyStatus = {
  active: "active",
  ended: "ended",
  pending: "pending",
} as const;
